name: Build release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload roadrash-cli
        uses: actions/upload-artifact@v2
        with:
          name: roadrash-cli
          path: 'target\release\roadrash-cli.exe'